const data = [
  {
    title: 'Touch-enabled Drawboard',
    url: 'draw-board-no-canvas',
    image: '',
    createdAt: '',
    description: '',
    technologies: [],
  },
  {
    title: 'My Blog',
    url: 'https://blog.elmosalamy.com',
    image: '',
    createdAt: '',
    description: '',
    technologies: [],
  },
  {
    title: 'Movie Search App',
    url: 'react-movie-search-app',
    image: '',
    createdAt: '',
    description: '',
    technologies: [],
  },
  {
    title: 'URL Shortener Microservice',
    url: 'https://stream-carnation-fang.glitch.me/',
    image: '',
    createdAt: '',
    description: '',
    technologies: [],
  },
  {
    title: 'Random Quotes Machine',
    url: '/random-quote-machine/',
    image: '',
    createdAt: '',
    description: '',
    technologies: [],
  },
  {
    title: 'Simple Todos',
    url: 'todo-react',
    image: '',
    createdAt: '',
    description: '',
    technologies: [],
  },
  {
    title: 'Microsoft Landing Remake',
    url: 'microsoft-landing-remake',
    image: '',
    createdAt: '',
    description: '',
    technologies: [],
  },
  {
    title: 'Trignometry-based Loader',
    url: 'trigonometry-loader',
    image: '',
    createdAt: '',
    description: '',
    technologies: [],
  },
  {
    title: 'Dice Roller',
    url: 'dice-roller',
    image: '',
    createdAt: '',
    description: '',
    technologies: [],
  },
  {
    title: 'Legacy Blog',
    url: 'blog',
    image: '',
    createdAt: '',
    description: '',
    technologies: [],
  },
  {
    title: 'Legacy Portfolio',
    url: 'portfolio',
    image: '',
    createdAt: '',
    description: '',
    technologies: [],
  },
]
